# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movie_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movie_app
	pod 'Alamofire'
	pod 'lottie-ios'
	pod 'SDWebImage'

  target 'movie_appTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'movie_appUITests' do
    # Pods for testing
  end

end
